TOPDIR=..\..

DYNAMICDIR=$(TOPDIR)\dynamiclib
STATICDIR=$(TOPDIR)\staticlib

CURDIR=.

CC      = cl
LD      = link
AR      = lib
RM      = del
CP      = copy /Y
MKDIR   = md.exe
MAKE    = nmake.exe

TARGET=example
STATICLIB_FILE = $(TARGET).lib
SHAREDLIB_FILE = $(TARGET).dll

HEADERS = crypt_md5.h crypt_aes.h crypt_mulmpi.h crypt_mpi.h crypt_mpn.h crypt_rsa.h crypt_sha256.h base64_code.h
SOURCES = crypt_md5.c crypt_aes.c crypt_mpi.c crypt_mpn.c crypt_rsa.c crypt_sha256.c base64_code.c
OBJECTS = $(SOURCES:.c=.obj)

!IFDEF UNICODE_MODE
!IF $(UNICODE_MODE) != 0
UNICODE_CFLAGS=-DUNICODE -D_UNICODE
!ELSE
UNICODE_CFLAGS=
!ENDIF
!ELSE
UNICODE_CFLAGS=
!ENDIF


!IFDEF MAKEVERBOSE

!IF $(MAKEVERBOSE) != 0
NOLOGO_CFLAGS = 
QUIETCMD=
NOLOG_MAKEFLAGS=
!ELSE
NOLOGO_CFLAGS = /nologo
QUIETCMD=@
NOLOG_MAKEFLAGS= /nologo
!ENDIF

!ELSE
QUIETCMD=@
NOLOGO_CFLAGS = /nologo
NOLOG_MAKEFLAGS= /nologo
!ENDIF

WINLIB_CFLAGS = -DWINLIB_DLL_EXPORT /MT



INC_CFLAGS = /I"$(CURDIR)" $(WINLIB_CFLAGS)
COM_CFLAGS = /Wall /wd"4711" /wd"4255" /wd"4710" /wd"4996"
REL_CFLAGS = /O2
DBG_CFLAGS = /ZI /Od

REL_LDFLAGS = /NOLOGO /DLL
DBG_LDFLAGS = /NOLOGO /DLL /DEBUG

CFLAGS  = $(UNICODE_CFLAGS) $(NOLOGO_CFLAGS) $(INC_CFLAGS) $(COM_CFLAGS) $(REL_CFLAGS)
LDFLAGS = $(REL_LDFLAGS)
ARFLAGS = /NOLOGO /WX

LIB_SOURCE = dllmain.c
LIB_OBJECTS = $(LIB_SOURCE:.c=.obj)
OBJECTS = $(LIB_OBJECTS)


all: $(STATICLIB_FILE) $(SHAREDLIB_FILE)


$(STATICLIB_FILE): $(OBJECTS)
    $(QUIETCMD)$(AR) $(ARFLAGS) /DEF -out:$@ $(OBJECTS)

$(SHAREDLIB_FILE): $(OBJECTS) $(STATICLIB_FILE)
    $(QUIETCMD)$(LD) $(LDFLAGS) /DLL -out:$@ $(OBJECTS)






.c.obj:
    $(QUIETCMD)$(CC) $(CFLAGS) -c -Fo$@ $<


clean:
    $(QUIETCMD)$(RM) *.pdb *.idb *.ilk *.exp *.lib *.dll 2>NUL || echo ""
    $(QUIETCMD)$(RM) $(OBJECTS) 2>NUL || echo ""
    $(QUIETCMD)$(RM) $(STATICLIB_FILE) $(SHAREDLIB_FILE) 2>NUL || echo ""
